[package]
name = "dioxus-resize-observer"
version = "0.2.0-alpha.1"
edition = "2021"
license = "MIT"
description = "Resize observer hooks for Dioxus."

[dependencies]
dioxus = "0.5.0-alpha.2"
dioxus-web = "0.5.0-alpha.2"
dioxus-signals = "0.5.0-alpha.2"
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["ResizeObserver", "ResizeObserverEntry"] }
dioxus-use-mounted = "0.2.0-alpha.1"
